import styles from "./globals.css";
import { Inria_Sans, Lily_Script_One, Reem_Kufi } from "next/font/google";

export const inria_sans = Inria_Sans({
    subsets: ['latin'],
    display: 'swap',
    weight: ["300", "400", "700"],
    variable: '--font-inria_sans',
})

export const lily_script_one = Lily_Script_One({
    subsets: ['latin'],
    display: 'swap',
    weight: "400",
    variable: '--font-lily_script',
})

export const reem_kufi = Reem_Kufi({
    subsets: ['latin'],
    display: 'swap',
    weight: ["400", "500", "600", "700"],
    variable: '--font-reem_kufi',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inria_sans.variable} ${lily_script_one.variable} ${reem_kufi.variable}`}>
      <body>
        {children}
        </body>
    </html>
  );
}
